### ISSUE TITLE
Where is test runner file?

### ISSUE THREAD

**Issue by YosAwed** [cta-wave/WMAS-deploy#1]
Readme.md said: 

Access test runner
To access the test runner and perform tests, open web-platform.test/_wave/.

However I couldn't find this in my container image. WebGL test runner was found, but is there whole test runner?

**Comment by FritzHeiden** [comment]
Could you try using port 8000? `web-platform.test:8000/_wave/`

**Comment by YosAwed** [comment]
> Could you try using port 8000? `web-platform.test:8000/_wave/`

Thanks!! It worked.
